### ISSUE TITLE
Implement Slide Input Logic

### ISSUE THREAD

**Issue by DanielHieber** [hnu-digihealth/patho-pix#3]
Read Slide

- [ ] Cleanup Label
- [ ] Genereate Tissue Mask
- [ ] Tiling

**Comment by muellerdo** [comment]
Tiling of mask:
- [ ] tiling of image
- [ ] os listdir of image tiles  
- [ ] extract coordinate pairs of image tiles
- [ ] create coordinate pairs histolab objects based on image tiles
- [ ] extract coordinate pairs histolab from mask slide
